/**********************************************************************************************************************
 * \file Motor.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/


/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "Motor.h"
/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/
void Motor_Init(void){
    MODULE_P10.IOCR0.B.PC1 = 0x10;
    MODULE_P02.IOCR4.B.PC7 = 0x10;

    MODULE_P10.IOCR0.B.PC2 = 0x10;
    MODULE_P02.IOCR4.B.PC6 = 0x10;

    GtmAtomPwm_Init();
    GtmAtomPwmA_SetDutyCycle(0);
    GtmAtomPwmB_SetDutyCycle(0);
}
void Motor_movChB(int dir){
    if (dir){
        MODULE_P10.OUT.B.P2 = 1; //방향
    }
    else{
        MODULE_P10.OUT.B.P2 = 0;
    }
    MODULE_P02.OUT.B.P6 = 0; //브레이크
    GtmAtomPwmB_SetDutyCycle(1000);
}
void Motor_stopChB(void){
    MODULE_P02.OUT.B.P6 = 1;
}
void Motor_movChB_PWM(int duty, int dir){
    GtmAtomPwmB_SetDutyCycle(duty*10);
    if (dir){
        MODULE_P10.OUT.B.P2 = 1; //회전방향
    }
    else{
        MODULE_P10.OUT.B.P2 = 0; //회전방향
    }
    MODULE_P02.OUT.B.P6 = 0; // 모터 brake 해제
}


//Motor A
void Motor_movChA(int dir){
    if (dir){
        MODULE_P10.OUT.B.P1 = 1; //방향
    }
    else{
        MODULE_P10.OUT.B.P1 = 0;
    }
    MODULE_P02.OUT.B.P7 = 0; //브레이크 해제
    GtmAtomPwmA_SetDutyCycle(1000);
}
void Motor_stopChA(void){
    MODULE_P02.OUT.B.P7 = 1;
}
void Motor_movChA_PWM(int duty, int dir){
    GtmAtomPwmA_SetDutyCycle(duty*10);
    if (dir){
        MODULE_P10.OUT.B.P1 = 1; //회전방향
    }
    else{
        MODULE_P10.OUT.B.P1 = 0; //회전방향
    }
    MODULE_P02.OUT.B.P7 = 0; // 모터 brake 해제
}
