/**********************************************************************************************************************
 * \file UltraSonic.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/


/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "UltraSonic.h"
#include "gpt12.h"
#include "stm.h"
#include "asclin.h"
/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/
volatile uint64 timer_start = 0;
volatile uint64 timer_end = 0;
volatile float distance=0.0;
volatile uint64 rear_duration;
volatile int measurement_ready = 0;  //
//uint64 howmany = 0;
/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/

void US_TestPinSetting(void){
    //test code for P11.10 echo interrupt, P11.11 trigger pin
    MODULE_P13.IOCR0.B.PC2 = 0x10; /* Set TRIG (P11.11)Pin to output */
    MODULE_P11.IOCR8.B.PC10 = 0x02; /* Set ECHO (P11.10) Pin to input */

    //button interrupt
    uint16 password = IfxScuWdt_getSafetyWatchdogPasswordInline();
    IfxScuWdt_clearSafetyEndinitInline(password);

    //Setting ERU//
    MODULE_SCU.EICR[3].B.EXIS0 = 3;//EICR[3].EXIS0 = ESR6, 3 is 3rd input (P11.10 = REQ6(3))

    MODULE_SCU.EICR[3].B.REN0 = 1;//rising edge
    MODULE_SCU.EICR[3].B.FEN0 = 1;//falling edge
    MODULE_SCU.EICR[3].B.EIEN0 = 1;//enable trigger pulse

    MODULE_SCU.EICR[3].B.INP0 = 0;//determination of output channel for trigger event (Register INP
    MODULE_SCU.IGCR[0].B.IGP0= 1;// configure output channels, outputgating unit OGU (Register IGPy)/ must set 1


    //ISR setting
    volatile Ifx_SRC_SRCR *src;
    src = (volatile Ifx_SRC_SRCR*) (&MODULE_SRC.SCU.SCUERU[0]);
    src -> B.SRPN = ISR_PRIORITY_US_ECHO_INT0;
    src -> B.TOS = 0;
    src -> B.CLRR = 1; //clear request
    src -> B.SRE = 1; // interrupt enable;
    IfxScuWdt_setSafetyEndinitInline(password);
}

void Ultrasonics_Init(void)
{
    /* Init Ultrasonic Pin */
//    MODULE_P13.IOCR0.B.PC2 = 0x10; /* Set TRIG (P13.2)Pin to output */
////    MODULE_P13.IOCR0.B.PC1 = 0x02; /* Set ECHO (P13.1) Pin to input */
//    MODULE_P15.IOCR4.B.PC4 = 0x02; /* Set ECHO (P13.1) Pin to input */

    IfxPort_setPinMode(&MODULE_P15, 4, IfxPort_Mode_inputPullUp);
    IfxStm_waitTicks(&MODULE_STM0, IfxStm_getTicksFromMicroseconds(&MODULE_STM0, 1000));
    IfxPort_setPinMode(&MODULE_P13, 2, IfxPort_Mode_outputPushPullGeneral);
    IfxStm_waitTicks(&MODULE_STM0, IfxStm_getTicksFromMicroseconds(&MODULE_STM0, 1000));
}


float Ultrasonic_ReadSensor_noFilt(void)
{
//    volatile int j = 0;
    uint64 timer_start, timer_end, rear_duration;
    float distance;
    /* Send Trigger Pulse */
    MODULE_P13.OUT.B.P2 = 1; // Rear TRIG_HIGH
//    for(j=0; j<1000; j++) continue;
//    MODULE_P13.OUT.B.P2 = 0; // Rear TRIG_LOW
    runGpt12_T6();//timer run => 10us


    /* Calculate Distance */
//    while (MODULE_P13.IN.B.P1 == 0); // wait for Rear ECHO_HIGH
    while (MODULE_P15.IN.B.P4 == 0);
    timer_start = getTimeUs();
//    while (MODULE_P13.IN.B.P1 == 1); // wait for Rear ECHO_LOW
    while (MODULE_P15.IN.B.P4 == 1);
    timer_end = getTimeUs();
    rear_duration = (timer_end - timer_start);
    distance = (float) 0.0343 * rear_duration / 2.0; // cm/us
    return distance;
}


void Ultrasonic_IR_Read_noFilt(void)
{
    /* Send Trigger Pulse */
    MODULE_P13.OUT.B.P2 = 1; // Rear TRIG_HIGH
//    my_printf("triggerpulse end\n");
    /* Calculate Distance */
//    while (MODULE_P13.IN.B.P1 == 0); // wait for Rear ECHO_HIGH
//    timer_start = getTimeUs();
//    while (MODULE_P13.IN.B.P1 == 1); // wait for Rear ECHO_LOW
//    timer_end = getTimeUs();
    ///
}

void US_IR_init(void){
    //button interrupt
    uint16 password = IfxScuWdt_getSafetyWatchdogPasswordInline();
    IfxScuWdt_clearSafetyEndinitInline(password);

    //MODULE_P15.IOCR4.B.PC4 = 0x02;//set port33.7 as pull-up input;

    //Setting ERU//
    MODULE_SCU.EICR[0].B.EXIS0 = 0;//EICR.EXIS  : ESR4,  (EICR2, EXIS0=ERS4, 0(REQ8,P33.7)
    MODULE_SCU.EICR[0].B.REN0 = 1;//rising edge
    MODULE_SCU.EICR[0].B.FEN0 = 1;//falling edge

    MODULE_SCU.EICR[0].B.EIEN0 = 1;//enable trigger pulse

    MODULE_SCU.EICR[0].B.INP0 = 0;//determination of output channel for trigger event (Register INP)

    MODULE_SCU.IGCR[0].B.IGP0= 1;// configure output channels, outputgating unit OGU (Register IGPy)

    //ISR
    volatile Ifx_SRC_SRCR *src;
    src = (volatile Ifx_SRC_SRCR*) (&MODULE_SRC.SCU.SCUERU[0]);
    src -> B.SRPN = ISR_PRIORITY_US_ECHO_INT0;
    src -> B.TOS = 0;
    src -> B.CLRR = 1; //clear request
    src -> B.SRE = 1; // interrupt enable;

    IfxScuWdt_setSafetyEndinitInline(password);
}
//void US_IR_Off(void){
//    MODULE_SCU.EICR[2].B.EIEN0 = 0;//enable trigger pulse
//}



IFX_INTERRUPT(US_Echo_test_Handler, 0 , ISR_PRIORITY_US_ECHO_INT0);
void US_Echo_test_Handler(void){
    if (MODULE_P11.IN.B.P10 == 1){
        timer_end = 0;
        timer_start = getTimeUs();
        measurement_ready = 0;
    }
    else{
        timer_end = getTimeUs();
        measurement_ready = 1;  // 측정 완료 신호
    }
}

void US_Echo_Int0_Handler(void){
//    MODULE_SCU.EIFR.B.INTF0 = 1;
//    MODULE_SCU.EIFR.B.INTF0 = 1;

    // EIFR 클리어 후 동기화 대기
//    volatile uint32 sync_dummy;
//    sync_dummy = MODULE_SCU.EIFR.U;  // EIFR read-back
//    sync_dummy = MODULE_P15.IN.U;    // 포트 전체 레지스터 읽기

    //howmany++;
    if (MODULE_P15.IN.B.P4 == 1){
        timer_end = 0;
        timer_start = getTimeUs();
        measurement_ready = 0;
    }
//    else if (MODULE_P15.IN.B.P4 == 0){
    else{
        timer_end = getTimeUs();
        measurement_ready = 1;  // 측정 완료 신호

    }
//    if (timer_start == 0 || timer_end == 0) return;
//    my_printf("s: %d, e: %d\n", timer_start, timer_end);
//    rear_duration = (timer_end - timer_start);
//    distance = 343 * (float)rear_duration / 20000; // cm/us

}
int is_ready(void){
    return measurement_ready;
}
float get_distance(void){
    if (!measurement_ready || timer_end == 0 || timer_start == 0) return 0;

    measurement_ready = 0;
    rear_duration = (timer_end - timer_start);
    distance = 343 * (float)rear_duration / 20000; // cm/us
    return distance;
}
