/**********************************************************************************************************************
 * \file Cpu0_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/


#include "Cpu0_Main.h"
//#include "CompilerTasking.h"
//IFX_ALIGN(4) IfxCpu_syncEvent g_cpuSyncEvent = 0;
//extern uint64 timer_start;
//extern uint64 timer_end;

extern ExtU_skid_steer_controller_T skid_steer_controller_U;
extern ExtY_skid_steer_controller_T skid_steer_controller_Y;

void core0_main(void)
{
    SYSTEM_INIT();
//
//    my_printf("Test start\n");
////    float dist = 0;
//    int i= 100;
//    int j = 0;
//    while(1){
//        int pwm = i-(j/100);
//        Motor_movChB_PWM(pwm,0);
//        j+=1;
////        my_printf("debg start\n");
////        MODULE_P13.OUT.B.P2 = 1; // Rear TRIG_HIGH
////        runGpt12_T6();//timer run => 10us
////        while(!is_ready()) {
////         }
////        my_printf("dist : %f\n", get_distance());
////        my_printf("dist : %f\n", )
////        my_printf("encoder : %d\n", get_encoder());
//        my_printf("pwm : %d , v : %f\n", pwm, get_timeV());
//        delay_ms(10);
//    };
    skid_steer_controller_initialize();

    while(1) {
        // ... (입력 데이터 준비) ...
        skid_steer_controller_U.v_target = 0.1;
        skid_steer_controller_U.w_target = 0.0;
        skid_steer_controller_U.enc_pulse_L = 0;
        skid_steer_controller_U.enc_pulse_R = 0;

        // ... (핵심 함수 호출) ...
        skid_steer_controller_step();

        // ... (출력 데이터 처리) ...
        ssv_set_motor_L(skid_steer_controller_Y.pwm_L,
                        skid_steer_controller_Y.dir_L,
                        skid_steer_controller_Y.brake_L);

        ssv_set_motor_R(skid_steer_controller_Y.pwm_R,
                        skid_steer_controller_Y.dir_R,
                        skid_steer_controller_Y.brake_R);

        // ... (10ms 대기) ...
        delay_ms(10);
    }
}
