/**********************************************************************************************************************
 * \file Buzzer.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/


/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "Buzzer.h"

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/
//buzzer
void Buzzer_Init(){
    MODULE_P02.IOCR0.B.PC3 = 0x10;
}

void Buzzer_Buzz(unsigned int hz){
//    volatile int loop = 1000000000 / hz / 2 / 5 / 2;
    //CPU clock = 200MHz = 5ns/cycle = T_per_cycle,
    //루프필요수 = 1sec /Hz /2(주기절반)  /T_per_cycle / 2(for문 한번당 2번 명령어 수행);


    volatile int loop = 1000000000 / hz / 2 / 5 ; //근데 debugger config보니까 100Mhz라서 *2해줌.
    MODULE_P02.OUT.B.P3 = 1;
    for (int i =0; i < loop ; i++){}

    MODULE_P02.OUT.B.P3 = 0;
    for (int i =0; i < loop ; i++){}
}


void Buzzer_Beep(unsigned int hz, int duration_ms){
    int unit_beep = 1000000000 / hz;

    int time = duration_ms*1000000;

    volatile int loop = time / unit_beep;
    for (int i=0; i < loop ; i++){
        Buzzer_Buzz(hz);
    }
}

void Play_Song(void){
    int song[] = {NOTE_E6, NOTE_D6, NOTE_E6, NOTE_D6, NOTE_E6, NOTE_B5, NOTE_D6, NOTE_C6, NOTE_A5};
    int duration[] = {
        8, 8, 8, 8, 8, 8, 8, 8, 4 //8분음표, 4분음표
    };

    for (int i=0; i < 9 ; i++){
        Buzzer_Beep(song[i], (1000/duration[i]));
    }
}

//IFX_INTERRUPT(IsrGpt1T3Handler, 1, ISR_PRIORITY_GPT1T3_TIMER);
//void IsrGpt1T3Handler(void){
//    MODULE_P02.OUT.B.P3 ^=1 ;
//}
int beepCnt = 0;
int beepOnOff = 0;
IFX_INTERRUPT(IsrGpt1T3Handler_Beep, 0, ISR_PRIORITY_GPT1T3_TIMER);
void IsrGpt1T3Handler_Beep(void)
{
    if ((beepCnt < beepOnOff) || (beepOnOff == 1)) { //beepOnOff이하에선 부저 끄고켜서 음을 만듦.
        MODULE_P02.OUT.B.P3 ^= 1;
    }
    else if (beepCnt < beepOnOff * 2) { //음 발생한 시간만큼 부저 꺼놓음.
        MODULE_P02.OUT.B.P3 = 0;
    }
    else {
         beepCnt = 0;
    }
    beepCnt++;
}
void setBeepCycle(int cycle){
 beepOnOff = cycle;
}
