/**********************************************************************************************************************
 * \file Cpu0_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/


#include "Cpu0_Main.h"
//#include "CompilerTasking.h"
//IFX_ALIGN(4) IfxCpu_syncEvent g_cpuSyncEvent = 0;
//extern uint64 timer_start;
//extern uint64 timer_end;


void core0_main(void)
{
    SYSTEM_INIT();

    my_printf("Test start\n");
//    float dist = 0;
    while(1){
//        my_printf("debg start\n");
        MODULE_P13.OUT.B.P2 = 1; // Rear TRIG_HIGH
        runGpt12_T6();//timer run => 10us
        while(!is_ready()) {
             // 강제로 CPU 점유 방지용 짧은 대기 또는 다른 작업 수행 가능
         }
        my_printf("dist : %f\n", get_distance());
        //my_printf("dist : %f\n", Ultrasonic_ReadSensor_noFilt());
//        delay_ms(2000);
    };
}
