/**********************************************************************************************************************
 * \file ERU.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

#ifndef ERU_C_
#define ERU_C_

/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "ERU.h"
/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/
#define ISR_PRIORITY_ERU_INT0 17


/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*-------------------------------------------------Data Structures---------------------------------------------------*/
/*********************************************************************************************************************/
 
/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/
void ScuEru_Init(void){
    //button interrupt
    uint16_t password = IfxScuWdt_getSafetyWatchdogPasswordInline();
    IfxScuWdt_clearSafetyEndinitInline(password);


    MODULE_P02.IOCR0.B.PC1 = 0x02; //set p2.1 as pull-up input;


    //Setting ERU//
    MODULE_SCU.EICR[1].B.EXIS0 = 1;//EICR.EXIS 레지스터 설정 : ESR2, 1번 신호 (EICR1번, EXIS0=ERS2, 1(REQ14,P2.1)

    MODULE_SCU.EICR[1].B.REN0 = 0;//rising edge 트리거 설정안함
    MODULE_SCU.EICR[1].B.FEN0 = 1;//falling edge 트리거 설정함.

    MODULE_SCU.EICR[1].B.EIEN0 = 1;//enable trigger pulse

    MODULE_SCU.EICR[1].B.INP0 = 0;//determination of output channel for trigger event (Register INP)

    MODULE_SCU.IGCR[0].B.IGP0= 1;// configure output channels, outputgating unit OGU (Register IGPy)

    //ISR 등록
    volatile Ifx_SRC_SRCR *src;
    src = (volatile Ifx_SRC_SRCR*) (&MODULE_SRC.SCU.SCUERU);
    src -> B.SRPN = ISR_PRIORITY_ERU_INT0;
    src -> B.TOS = 0;
    src -> B.CLRR = 1; //clear request
    src -> B.SRE = 1; // interrupt enable;

    IfxScuWdt_setSafetyEndinitInline(password);

}


IFX_INTERRUPT(SCUERU_Int0_Handler, 0 , ISR_PRIORITY_ERU_INT0);
void SCUERU_Int0_Handler(void){
    my_printf("SCU_ERU_INT0!\n");
}



#endif /* ERU_C_ */
