/**********************************************************************************************************************
 * \file EV_ADC.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/


/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "EV_ADC.h"
/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/
#define GROUPID_3     IfxEvadc_GroupId_3

#define AN24_CHID      1
#define AN25_CHID      0
/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/
/*********************************************************************************************************************/
IfxEvadc_Adc         g_evadc_EasyModule;
IfxEvadc_Adc_Group   g_adcGroup_EasyModule;
IfxEvadc_Adc_Channel g_adcChannel_VR; /* Easy Module Shield Variable Resistor */
IfxEvadc_Adc_Channel g_adcChannel_PR; /* Easy Module Shield Photo resistor */
Ifx_EVADC_G_RES g_result;                                       /* Variable to store the result of the measurement  */

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/
void Evadc_Init(void)
{
    /* Create configuration */
    IfxEvadc_Adc_Config adcConfig;
    IfxEvadc_Adc_initModuleConfig(&adcConfig, &MODULE_EVADC);

    /* Initialize module */
    IfxEvadc_Adc_initModule(&g_evadc_EasyModule, &adcConfig);
    /* Function to initialize the EVADC group with default parameters */
    /* Create and initialize group configuration with default values */
    IfxEvadc_Adc_GroupConfig adcGroupConfig;
    IfxEvadc_Adc_initGroupConfig(&adcGroupConfig, &g_evadc_EasyModule);
    /* Setting user configuration using group 3 */
    adcGroupConfig.groupId = GROUPID_3;
    adcGroupConfig.master = GROUPID_3;
    /* Enable queued source */
    adcGroupConfig.arbiter.requestSlotQueue0Enabled = TRUE;
    /* Enable all gates in "always" mode (no edge detection) */
    adcGroupConfig.queueRequest[0].triggerConfig.gatingMode = IfxEvadc_GatingMode_always;
    /* Initialize the group */
    IfxEvadc_Adc_initGroup(&g_adcGroup_EasyModule, &adcGroupConfig);

    /* Function to initialize the EVADC channel */
    /* Create channel configuration */
    IfxEvadc_Adc_ChannelConfig adcChannelConfig[2];

    // Init Variable Register Channel
    /* Initialize the configuration with default values */
    IfxEvadc_Adc_initChannelConfig(&adcChannelConfig[0], &g_adcGroup_EasyModule);
    /* Select the channel ID and the respective result register */
    adcChannelConfig[0].channelId = (IfxEvadc_ChannelId)(AN25_CHID);
    adcChannelConfig[0].resultRegister = (IfxEvadc_ChannelResult)(AN25_CHID);
    /* Initialize the channel */
    IfxEvadc_Adc_initChannel(&g_adcChannel_VR, &adcChannelConfig[0]);

    // Init Photo Register channel
    /* Initialize the configuration with default values */
    IfxEvadc_Adc_initChannelConfig(&adcChannelConfig[1], &g_adcGroup_EasyModule);
    /* Select the channel ID and the respective result register */
    adcChannelConfig[1].channelId = (IfxEvadc_ChannelId)(AN24_CHID);
    adcChannelConfig[1].resultRegister = (IfxEvadc_ChannelResult)(AN24_CHID);
    /* Initialize the channel */
    IfxEvadc_Adc_initChannel(&g_adcChannel_PR, &adcChannelConfig[1]);

    /* Function to add the channel to a queue */
    /* Add channel to queue with refill option enabled */
    IfxEvadc_Adc_addToQueue(&g_adcChannel_VR, IfxEvadc_RequestSource_queue0, IFXEVADC_QUEUE_REFILL);
    IfxEvadc_Adc_addToQueue(&g_adcChannel_PR, IfxEvadc_RequestSource_queue0, IFXEVADC_QUEUE_REFILL);
    /* Start the queue */
    IfxEvadc_Adc_startQueue(&g_adcGroup_EasyModule, IfxEvadc_RequestSource_queue0);

}

unsigned int Evadc_readVR(void)
{
    Ifx_EVADC_G_RES conversionResult;

    /* Wait for valid result */
    do
    {
        conversionResult = IfxEvadc_Adc_getResult(&g_adcChannel_VR); /* Read the result of the channel */
    } while(!conversionResult.B.VF);

    return conversionResult.B.RESULT;
}

unsigned int Evadc_readPR(void)
{
    Ifx_EVADC_G_RES conversionResult;

    /* Wait for valid result */
    do
    {
        conversionResult = IfxEvadc_Adc_getResult(&g_adcChannel_PR); /* Read the result of the channel */
    } while(!conversionResult.B.VF);

    return conversionResult.B.RESULT;
}
