/**********************************************************************************************************************
 * \file GPIO.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/


/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "GPIO.h"

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/
void GPIO_Init(void){
    //LED1
    MODULE_P23.IOCR0.B.PC1 = 0x10; // P23.1 LED1 Output setting
    MODULE_P23.OUT.B.P1 = 0; // LED1 OFF is default;

    //LED2
    MODULE_P23.IOCR0.B.PC3 = 0x10; // P23.3 LED2 Output setting
    MODULE_P23.OUT.B.P3 = 0; // LED2 OFF is default;

//    MODULE_P02.IOCR0.B.PC0 = 0x2; // SW1
//    MODULE_P02.IOCR0.B.PC1 = 0x2; // Sw2
}

void GPIO_SetLed(unsigned char num_LED, unsigned char onOff){
    if (num_LED == 1){
        MODULE_P23.OUT.B.P1 = onOff;
//        if (onOff==0){
//            MODULE_P10.OUT.B.P2 = 0; // LED1 OFF
//        }
//        else if (onOff == 1){
//            MODULE_P10.OUT.B.P2 = 1; // LED1 ON
//        }
    }
    else if (num_LED == 2){
        MODULE_P23.OUT.B.P3 = onOff;
//        if (onOff==0){
//            MODULE_P10.OUT.B.P1 = 0; // LED1 OFF
//        }
//        else if (onOff == 1){
//            MODULE_P10.OUT.B.P1 = 1; // LED1 ON
//        }
    }
}
void GPIO_ToggleLed(unsigned char num_LED){
    if (num_LED == 1){
        MODULE_P23.OUT.B.P1 ^= 1; // LED1 ONOFF
    }
    else if (num_LED == 2){
        MODULE_P23.OUT.B.P3 ^= 1; // LED1 OFF is default;
    }
}

void OMR_ToggleLed(unsigned char num_LED){
    if (num_LED == 1){
        MODULE_P10.OMR.U = ((1 << 18) | (1<<2));
//        MODULE_P10.OMR.B.PS2 = 1;
    }
    else if (num_LED == 2){
        MODULE_P10.OMR.U = ((1 << 17) | (1<<1));
//        MODULE_P10.OMR.B.PCL1 = 1; // LED1 OFF is default;
//        MODULE_P10.OMR.B.PS1 = 1;
    }
}


int GPIO_getSW1(void){
    return (MODULE_P02.IN.B.P0==0);
}
int GPIO_getSW2(void){
    return (MODULE_P02.IN.B.P1==0); //pull-up device ; default is high;
}


void delay_ms(unsigned int ms)
{
    waitTime(IfxStm_getTicksFromMilliseconds(BSP_DEFAULT_TIMER, ms));    /* Wait 500 milliseconds            */
}


/* LED Toggle (Left, Right, Both) & GPT2 ISR*/
static volatile unsigned int Left_Led_Flag = 0;
static volatile unsigned int Right_Led_Flag = 0;
void Left_ToggleLed(void)
{
    stopGpt12_T6();
    Left_Led_Flag = 1;
    Right_Led_Flag = 0;
    runGpt12_T6();
}

void Right_ToggleLed(void)
{
    stopGpt12_T6();
    Left_Led_Flag = 0;
    Right_Led_Flag = 1;
    runGpt12_T6();
}

void Both_ToggleLed(void)
{
    stopGpt12_T6();
    Left_Led_Flag = 1;
    Right_Led_Flag = 1;
    runGpt12_T6();
}

static volatile unsigned int g_Cnt10us=0;
IFX_INTERRUPT(IsrGpt2T6LEDHandler, 0 , ISR_PRIORITY_GPT2T6_TIMER);
void IsrGpt2T6LEDHandler(void){
    g_Cnt10us++;
    if (g_Cnt10us >= 50000){ //500ms = 500000us
        MODULE_P23.OUT.B.P1 ^= Left_Led_Flag;
        MODULE_P23.OUT.B.P3 ^= Right_Led_Flag;
        g_Cnt10us=0;
    }
}











