/**********************************************************************************************************************
 * \file GPIO.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/


/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "GPIO.h"

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/
void GPIO_Init(void){
    //LED1
    MODULE_P10.IOCR0.B.PC2 = 0x10; //핀 output설정 완료
    MODULE_P10.OUT.B.P2 = 0; // LED1 OFF is default;

    //LED2
    MODULE_P10.IOCR0.B.PC1 = 0x10; //핀 output설정 완료
    MODULE_P10.OUT.B.P1 = 0; // LED1 OFF is default;

    //SW1
    MODULE_P02.IOCR0.B.PC0 = 0x2;

    //SW2
    MODULE_P02.IOCR0.B.PC1 = 0x2;
}

void GPIO_SetLed(unsigned char num_LED, unsigned char onOff){
    if (num_LED == 1){
        if (onOff==0){
            MODULE_P10.OUT.B.P2 = 0; // LED1 OFF
        }
        else if (onOff == 1){
            MODULE_P10.OUT.B.P2 = 1; // LED1 ON
        }
    }
    else if (num_LED == 2){
        if (onOff==0){
            MODULE_P10.OUT.B.P1 = 0; // LED1 OFF
        }
        else if (onOff == 1){
            MODULE_P10.OUT.B.P1 = 1; // LED1 ON
        }
    }
}
void GPIO_ToggleLed(unsigned char num_LED){
    if (num_LED == 1){
        MODULE_P10.OUT.B.P2 ^= 1; // LED1 ONOFF
    }
    else if (num_LED == 2){
        MODULE_P10.OUT.B.P1 ^= 1; // LED1 OFF is default;
    }
}

void OMR_ToggleLed(unsigned char num_LED){
    if (num_LED == 1){
        MODULE_P10.OMR.U = ((1 << 18) | (1<<2));
//        MODULE_P10.OMR.B.PS2 = 1;
    }
    else if (num_LED == 2){
        MODULE_P10.OMR.U = ((1 << 17) | (1<<1));
//        MODULE_P10.OMR.B.PCL1 = 1; // LED1 OFF is default;
//        MODULE_P10.OMR.B.PS1 = 1;
    }
}


int GPIO_getSW1(void){
    return (MODULE_P02.IN.B.P0==0);
}
int GPIO_getSW2(void){
    return (MODULE_P02.IN.B.P1==0); //pull-up device ; default is high;
}

void delay(void){
    volatile int i=0;
    while (i < 10000000){ //delay 기능 구현 volatile
        i++;
    }
    i=0;
}
void delayMS(int duration_ms){
    int unit_beep = 100000000; //100MHz CPU clock = 100000000 tick / 1s

    int time = duration_ms*1000; //1s

    int loop = time / unit_beep  / 3; //
    volatile int i =0;
    while (i < loop){
        i++;
    }
}
void delay_ms(unsigned int ms)
{
    waitTime(IfxStm_getTicksFromMilliseconds(BSP_DEFAULT_TIMER, ms));    /* Wait 500 milliseconds            */
}













