/**********************************************************************************************************************
 * \file gpt12.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/


/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/

#include "gpt12.h"
/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/

void gpt1_init(void){
    //use CPU1 !!!! can't use CPU0;
    IfxScuWdt_clearCpuEndinit(IfxScuWdt_getGlobalEndinitPassword());//DISR watch dog time
    MODULE_GPT120.CLC.U = 0; //DISR enable
    IfxScuWdt_setCpuEndinit(IfxScuWdt_getGlobalEndinitPassword());

    //T3 Timer
    MODULE_GPT120.T3CON.B.T3M = 0x0; //set timer mode
    //prescaler ; 1024
    MODULE_GPT120.T3CON.B.T3I = 0x5;
    MODULE_GPT120.T3CON.B.BPS1 = 0x2;

    MODULE_GPT120.T3CON.B.T3UD = 0x1; //direction : count down
//    MODULE_GPT120.T3.U = 375; // 1clock = 10.24us => 375clock = 3840.00 us => 130hz,7692us
    MODULE_GPT120.T3.U =  93; //5

    //T2 Timer
    MODULE_GPT120.T2CON.B.T2M = 0x4; //set reload mode. //Part2M, p30-15
    MODULE_GPT120.T2CON.B.T2I = 0x7; //reload input mode ; Any(rising/falling) edge T3OTL; Table220
//    MODULE_GPT120.T2.U = 375;
    MODULE_GPT120.T2.U = 93;

    //init iterrupt
    MODULE_SRC.GPT12.GPT12[0].T3.B.SRPN = ISR_PRIORITY_GPT1T3_TIMER; //interrupt priority set
    MODULE_SRC.GPT12.GPT12[0].T3.B.CLRR = 1; //clear request
    MODULE_SRC.GPT12.GPT12[0].T3.B.TOS = 2; //cpu1 (from part1 M p16-5)
    MODULE_SRC.GPT12.GPT12[0].T3.B.SRE = 1; //interrupt enable

//    MODULE_ASCLIN0.FLAGSENABLE.B.RFLE =1; // enable RXFIFO fill level flag; << why?

    MODULE_GPT120.T3CON.B.T3R = 1; //timer run.
}


void gpt2_init(void){

    //part2 p30-58 default
    IfxScuWdt_clearCpuEndinit(IfxScuWdt_getGlobalEndinitPassword());//
    MODULE_GPT120.CLC.U = 0; //DISR enable
    IfxScuWdt_setCpuEndinit(IfxScuWdt_getGlobalEndinitPassword());

    MODULE_GPT120.T6CON.B.T6M = 0x0; //set timer mode (p30-48)

    //prescaler set 4 (ref Table 227, part2 M p30-52) ==> CPU 100MHz 100/4=25MHz
    MODULE_GPT120.T6CON.B.BPS2= 0x0; //prescaler parameter
    MODULE_GPT120.T6CON.B.T6I = 0x0; //prescaler parameter

    MODULE_GPT120.T6CON.B.T6UD = 0x1; //config: count down

    MODULE_GPT120.T6CON.B.T6OE = 0x1; //overflow/under flow output enable
    MODULE_GPT120.T6CON.B.T6SR = 0x1; //reload from register CAPREL enabled

    MODULE_GPT120.T6.U = 250u; //25MHz = 250u tick =  10us.

    MODULE_GPT120.CAPREL.U = 250u; //set CAPREL reload value

    volatile Ifx_SRC_SRCR *src;
    src = (volatile Ifx_SRC_SRCR*)(&MODULE_SRC.GPT12.GPT12[0].T6);
    src -> B.SRPN = ISR_PRIORITY_GPT2T6_TIMER;
    src -> B.TOS = 0;
    src -> B.CLRR = 1;
    src -> B.SRE  = 1;
//    runGpt12_T6();//timer run
    //t3R=1;
}





//static volatile unsigned int cntDelay = 0;
static volatile unsigned int g_Cnt10us=0;
IFX_INTERRUPT(IsrGpt2T6BuzzerHandler, 0 , ISR_PRIORITY_GPT2T6_TIMER);
void IsrGpt2T6USHandler(void){
    g_Cnt10us++;
    if (g_Cnt10us >= 2){
        MODULE_P11.OUT.B.P12 = 0; // Rear TRIG_LOW
        stopGpt12_T6();
        g_Cnt10us=0;
    }
}
void IsrGpt2T6BuzzerHandler(void){
    g_Cnt10us++;
    if (g_Cnt10us >= 2){
        MODULE_P13.OUT.B.P2 = 0; // Rear TRIG_LOW
        stopGpt12_T6();
        g_Cnt10us=0;
    }
}


//IFX_INTERRUPT(IsrGpt2T6Handler, 0 , ISR_PRIORITY_GPT2T6_TIMER);
void IsrGpt2T6Handler(void){
    g_Cnt10us++;
    if (g_Cnt10us % 10000 ==0) {Task_100ms();}
    if (g_Cnt10us % 20000 ==0) {Task_200ms();}
    if (g_Cnt10us % 50000 ==0) {Task_500ms();}

}
void runGpt12_T6(void){
    MODULE_GPT120.T6CON.B.T6R = 1;
}
void stopGpt12_T6(void){
    MODULE_GPT120.T6CON.B.T6R = 0;
}


void Task_100ms(void){
    if(GPIO_getSW1()){GPIO_SetLed(2,1);}
    else {GPIO_SetLed(2,0);}
}
void Task_200ms(void){
    my_printf("Task 200ms Called!\n");
}
void Task_500ms(void){
    GPIO_ToggleLed(1);
}

