/**********************************************************************************************************************
 * \file gtm_atom_pwm.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/


/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "gtm_atom_pwm.h"

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/
IfxGtm_Atom_Pwm_Config g_atomConfig_PwmA;
IfxGtm_Atom_Pwm_Config g_atomConfig_PwmB;
IfxGtm_Atom_Pwm_Driver g_atomDriver_PwmA;
IfxGtm_Atom_Pwm_Driver g_atomDriver_PwmB;

IfxGtm_Atom_Pwm_Config g_atomConfig;                            /* Timer configuration structure                    */
IfxGtm_Atom_Pwm_Driver g_atomDriver;                            /* Timer Driver structure                           */
/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/
//void GtmAtomPwm_Init (void)
//{
//    /* Enable GTM */
//    uint16 psw = IfxScuWdt_getCpuWatchdogPassword();
//    IfxScuWdt_clearCpuEndinit(psw);
//    MODULE_GTM.CLC.B.DISR = 0;
//    IfxScuWdt_setCpuEndinit(psw);
//
//    IfxGtm_Cmu_setClkFrequency(&MODULE_GTM, IfxGtm_Cmu_Clk_0, CLK_FREQ); /* Set the CMU clock 0 frequency */
//    IfxGtm_Cmu_enableClocks(&MODULE_GTM, IFXGTM_CMU_CLKEN_CLK0); /* Enable the CMU clock 0 */
//    IfxGtm_Cmu_setClkFrequency(&MODULE_GTM, IfxGtm_Cmu_Clk_1, CLK_FREQ);
//    IfxGtm_Cmu_enableClocks(&MODULE_GTM, IFXGTM_CMU_CLKEN_CLK1);
//
//    IfxGtm_Atom_Pwm_initConfig(&g_atomConfig, &MODULE_GTM); /* Initialize default parameters */
//
//    g_atomConfig.atom = PWM_B.atom; /* Select the ATOM depending on the LED */ //10.3 연결된 ATOM 신호 설정. ATOM1, ch3번
//    g_atomConfig.atomChannel = PWM_B.channel; /* Select the channel depending on the LED */
//    g_atomConfig.period = PWM_PERIOD; /* Set timer period *///주기는 1000us = 1Mhz
//    g_atomConfig.pin.outputPin = &PWM_B; /* Set LED as output */
//    g_atomConfig.synchronousUpdateEnabled = TRUE; /* Enable synchronous update */
//
//    IfxGtm_Atom_Pwm_init(&g_atomDriver, &g_atomConfig); /* Initialize the PWM */
//    IfxGtm_Atom_Pwm_start(&g_atomDriver, TRUE); /* Start the PWM */
//}
void GtmAtomPwm_Init(void)
{
    /* Enable GTM */
    uint16 psw = IfxScuWdt_getCpuWatchdogPassword();
    IfxScuWdt_clearCpuEndinit(psw);
    MODULE_GTM.CLC.B.DISR = 0;
    IfxScuWdt_setCpuEndinit(psw);                                     /* Enable GTM                           */

    IfxGtm_Cmu_setClkFrequency(&MODULE_GTM, IfxGtm_Cmu_Clk_0, CLK_FREQ);    /* Set the CMU clock 0 frequency        */
    IfxGtm_Cmu_enableClocks(&MODULE_GTM, IFXGTM_CMU_CLKEN_CLK0);            /* Enable the CMU clock 0               */
//    IfxGtm_Cmu_setClkFrequency(&MODULE_GTM, IfxGtm_Cmu_Clk_1, CLK_FREQ);
//    IfxGtm_Cmu_enableClocks(&MODULE_GTM, IFXGTM_CMU_CLKEN_CLK1);

    IfxGtm_Atom_Pwm_initConfig(&g_atomConfig_PwmA, &MODULE_GTM);
//    IfxGtm_Atom_Pwm_initConfig(&g_atomConfig, &MODULE_GTM);                 /* Initialize default parameters        */

    g_atomConfig_PwmA.atom = PWM_A.atom;
    g_atomConfig_PwmA.atomChannel = PWM_A.channel;
    g_atomConfig_PwmA.period = PWM_PERIOD;
    g_atomConfig_PwmA.pin.outputPin = &PWM_A;
    g_atomConfig_PwmA.synchronousUpdateEnabled = TRUE;

    IfxGtm_Atom_Pwm_init(&g_atomDriver_PwmA, &g_atomConfig_PwmA);
    IfxGtm_Atom_Pwm_start(&g_atomDriver_PwmA, TRUE);


    IfxGtm_Cmu_setClkFrequency(&MODULE_GTM, IfxGtm_Cmu_Clk_1, CLK_FREQ);
    IfxGtm_Cmu_enableClocks(&MODULE_GTM, IFXGTM_CMU_CLKEN_CLK1);

    IfxGtm_Atom_Pwm_initConfig(&g_atomConfig_PwmB, &MODULE_GTM);

    g_atomConfig_PwmB.atom = PWM_B.atom;                                       /* Select the ATOM depending on the LED     */
    g_atomConfig_PwmB.atomChannel = PWM_B.channel;                             /* Select the channel depending on the LED  */
    g_atomConfig_PwmB.period = PWM_PERIOD;                                   /* Set timer period                         */
    g_atomConfig_PwmB.pin.outputPin = &PWM_B;                                  /* Set LED as output                        */
    g_atomConfig_PwmB.synchronousUpdateEnabled = TRUE;                       /* Enable synchronous update                */

    IfxGtm_Atom_Pwm_init(&g_atomDriver_PwmB, &g_atomConfig_PwmB);                 /* Initialize the PWM                       */
    IfxGtm_Atom_Pwm_start(&g_atomDriver_PwmB, TRUE);                         /* Start the PWM                            */
}

//void GtmAtomPwm_SetDutyCycle(uint32 dutyCycle){
//    g_atomConfig.dutyCycle = dutyCycle;
//    IfxGtm_Atom_Pwm_init(&g_atomDriver, &g_atomConfig);
//}
void GtmAtomPwmA_SetDutyCycle(uint32 dutyCycle)
{
    g_atomConfig_PwmA.dutyCycle = dutyCycle;                 /* Set duty cycle                                           */
    IfxGtm_Atom_Pwm_init(&g_atomDriver_PwmA, &g_atomConfig_PwmA); /* Re-initialize the PWM                                    */
}

void GtmAtomPwmB_SetDutyCycle(uint32 dutyCycle)
{
    g_atomConfig_PwmB.dutyCycle = dutyCycle;                 /* Set duty cycle                                           */
    IfxGtm_Atom_Pwm_init(&g_atomDriver_PwmB, &g_atomConfig_PwmB); /* Re-initialize the PWM                                    */
}
