/**********************************************************************************************************************
 * \file UltraSonic.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/


/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "UltraSonic.h"
#include "gpt12.h"
#include "stm.h"
/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/
uint64 timer_start = 0;
uint64 timer_end = 0;
float distance =0.0;
uint64 rear_duration;
/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/
void Ultrasonics_Init(void)
{
    /* Init Ultrasonic Pin */
    MODULE_P13.IOCR0.B.PC2 = 0x10; /* Set TRIG (P13.2)Pin to output */
//    MODULE_P13.IOCR0.B.PC1 = 0x02; /* Set ECHO (P13.1) Pin to input */
    MODULE_P15.IOCR4.B.PC4 = 0x02; /* Set ECHO (P13.1) Pin to input */
}

float Ultrasonic_ReadSensor_noFilt(void)
{
//    volatile int j = 0;
    uint64 timer_start, timer_end, rear_duration;
    float distance;
    /* Send Trigger Pulse */
    MODULE_P13.OUT.B.P2 = 1; // Rear TRIG_HIGH
//    for(j=0; j<1000; j++) continue;
//    MODULE_P13.OUT.B.P2 = 0; // Rear TRIG_LOW
    runGpt12_T6();//timer run => 10us 이후 자동으로 trig신호 끄고 타이머 OFF


    /* Calculate Distance */
//    while (MODULE_P13.IN.B.P1 == 0); // wait for Rear ECHO_HIGH
    while (MODULE_P15.IN.B.P4 == 0);
    timer_start = getTimeUs();
//    while (MODULE_P13.IN.B.P1 == 1); // wait for Rear ECHO_LOW
    while (MODULE_P15.IN.B.P4 == 1);
    timer_end = getTimeUs();
    rear_duration = (timer_end - timer_start);
    distance = (float) 0.0343 * rear_duration / 2.0; // cm/us
    return distance;
}


void Ultrasonic_IR_Read_noFilt(void)
{
    /* Send Trigger Pulse */
    MODULE_P13.OUT.B.P2 = 1; // Rear TRIG_HIGH
    runGpt12_T6();//timer run => 20us 이후 자동으로 trig신호 끄고 타이머 OFF

//    my_printf("triggerpulse end\n");
    /* Calculate Distance */
//    while (MODULE_P13.IN.B.P1 == 0); // wait for Rear ECHO_HIGH
//    timer_start = getTimeUs();
//    while (MODULE_P13.IN.B.P1 == 1); // wait for Rear ECHO_LOW
//    timer_end = getTimeUs();
    ///
}

void US_IR_init(void){
    //button interrupt
    uint16 password = IfxScuWdt_getSafetyWatchdogPasswordInline();
    IfxScuWdt_clearSafetyEndinitInline(password);

    MODULE_P15.IOCR4.B.PC4 = 0x02;//set port33.7 as pull-up input;

    //Setting ERU//
    MODULE_SCU.EICR[0].B.EXIS0 = 0;//EICR.EXIS 레지스터 설정 : ESR4, 0번 신호 (EICR2번, EXIS0=ERS4, 0(REQ8,P33.7)

    MODULE_SCU.EICR[0].B.REN0 = 1;//rising edge 트리거 설정
    MODULE_SCU.EICR[0].B.FEN0 = 1;//falling edge 트리거 설정함.

    MODULE_SCU.EICR[0].B.EIEN0 = 1;//enable trigger pulse

    MODULE_SCU.EICR[0].B.INP0 = 0;//determination of output channel for trigger event (Register INP)

    MODULE_SCU.IGCR[0].B.IGP0= 1;// configure output channels, outputgating unit OGU (Register IGPy)

    //ISR 등록
    volatile Ifx_SRC_SRCR *src;
    src = (volatile Ifx_SRC_SRCR*) (&MODULE_SRC.SCU.SCUERU);
    src -> B.SRPN = ISR_PRIORITY_US_ECHO_INT0;
    src -> B.TOS = 0;
    src -> B.CLRR = 1; //clear request
    src -> B.SRE = 1; // interrupt enable;

    IfxScuWdt_setSafetyEndinitInline(password);
}
//void US_IR_Off(void){
//    MODULE_SCU.EICR[2].B.EIEN0 = 0;//enable trigger pulse
//}



IFX_INTERRUPT(US_Echo_Int0_Handler, 0 , ISR_PRIORITY_US_ECHO_INT0);

volatile uint64 howmany = 0;
void US_Echo_Int0_Handler(void){
    howmany++;

    if (MODULE_P15.IN.B.P4 == 1){
        timer_end = 0;
        timer_start = getTimeUs();
    }
    else if (MODULE_P15.IN.B.P4 == 0){
        timer_end = getTimeUs();
    }
    if (timer_start == 0 || timer_end == 0) return;

    my_printf("s: %d, e: %d\n", timer_start, timer_end);
    rear_duration = (timer_end - timer_start);
    distance = 0.0343 * (float)rear_duration / 2.0; // cm/us
    my_printf("dist: %f", distance);

}


//스위치 누르고 거리 가까워지면 비프음 빨리지게 만들어보기
